### ISSUE TITLE
Toggle to the test panel to activate the package: cmd-ctrl-x does not work

### ISSUE THREAD

**Issue by idev4u** [moxley/atom-ruby-test#105]
[Enter steps to reproduce:]

1. cmd-ctrl-x

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [notifications](https://github.com/atom/notifications) package 0.67.2

### Stack Trace

Uncaught TypeError: Cannot read property 'nodeName' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/command-logger.js:81

TypeError: Cannot read property 'nodeName' of undefined
    at CommandLogger.module.exports.CommandLogger.logCommand (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/command-logger.js:81:1)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/command-logger.js:33:1
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:246:1)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:1)
    at RubyTestView.module.exports.RubyTestView.toggle (/packages/ruby-test/lib/ruby-test-view.coffee:38:19)
    at /packages/ruby-test/lib/ruby-test-view.coffee:15:65)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:36.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:32.8.0 ruby-test:toggle (div.package-detail.panels-item)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
busy-signal 1.4.1 
concourse-vis 1.4.0 
file-icons 2.1.7 
intentions 1.1.2 
language-rspec 0.6.2 
linter 2.1.4 
linter-rubocop 2.1.1 
linter-ruby 1.2.5 
linter-ui-default 1.6.0 
platformio-ide-terminal 2.5.1 
rspec 0.3.2 
ruby-quick-test 0.4.0 
ruby-test 1.0.2 
script 3.15.0 
toggle-quotes 1.0.1 
trailing-spaces 0.4.0 
```

**Comment by nolanpro** [comment]
Does this only happen when no windows are open and you hit ctrl+cmd+x?

**Comment by idev4u** [comment]
Only if no window or the settings window is open. Open one of my spec files and do the toogle fix the problem.
Now it works for me. Thanks
