### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by matt-thomson** [moxley/atom-ruby-test#51]
[Enter steps to reproduce below:]

1. Pressed Ctrl+Cmd+T to run tests.

**Atom Version**: 0.196.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [ruby-test](https://github.com/moxley/atom-ruby-test) package, v0.9.6

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/matt/.atom/packages/ruby-test/lib/source-info.coffee:32

TypeError: undefined is not a function
  at SourceInfo.module.exports.SourceInfo.currentLine (/Users/matt/.atom/packages/ruby-test/lib/source-info.coffee:34:36)
  at TestRunner.module.exports.TestRunner.command (/Users/matt/.atom/packages/ruby-test/lib/test-runner.coffee:33:48)
  at TestRunner.command (/Users/matt/.atom/packages/ruby-test/lib/test-runner.coffee:1:1)
  at TestRunner.module.exports.TestRunner.run (/Users/matt/.atom/packages/ruby-test/lib/test-runner.coffee:15:28)
  at RubyTestView.module.exports.RubyTestView.runTest (/Users/matt/.atom/packages/ruby-test/lib/ruby-test-view.coffee:72:13)
  at RubyTestView.module.exports.RubyTestView.testFile (/Users/matt/.atom/packages/ruby-test/lib/ruby-test-view.coffee:53:6)
  at atom-workspace.<anonymous> (/Users/matt/.atom/packages/ruby-test/lib/ruby-test-view.coffee:24:68)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:16.9.0 core:close (atom-text-editor.editor.is-focused)
     -0:06.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -0:03.2.0 core:move-down (atom-text-editor.editor.mini)
     -0:03.0 core:confirm (atom-text-editor.editor.mini)
     -0:01.6.0 ruby-test:test-file (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "racer"
    ]
  },
  "ruby-test": {
    "rspecAllCommand": "bin/rspec --tty spec",
    "rspecSingleCommand": "bin/rspec --tty {relative_path}:{line_number}",
    "rspecFileCommand": "bin/rspec --tty {relative_path}"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.12.1
autocomplete-ruby, v0.1.0
language-rust, v0.4.3
linter, v0.12.1
linter-rubocop, v0.2.3
pretty-json, v0.3.3
ruby-bundler, v0.2.1
ruby-test, v0.9.6
seti-syntax, v0.4.0
seti-ui, v0.6.3
test-jumper, v0.3.0

# Dev
No dev packages
```

**Comment by matt-thomson** [comment]
Looks like this is fixed in master, so will go away with the next release.
