### ISSUE TITLE
not working for win 7

### ISSUE THREAD

**Issue by dbwest** [moxley/atom-ruby-test#86]
[Enter steps to reproduce below:]

1. Use Win 7
2. Run a cucumber file from atom

**Atom Version**: 1.7.3
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [ruby-test](https://github.com/moxley/atom-ruby-test) package, v0.9.17

### Stack Trace

Uncaught Error: EPERM: operation not permitted, open 'C:\xxx\my.feature'

```
At C:\Users\westd\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1108

Error: EPERM: operation not permitted, open 'C:\dsfasdf'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at Object.fsPlus.writeFileSync (C:\Users\westd\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (C:\Users\westd\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:282:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (C:\Users\westd\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:420:21)
    at File.module.exports.File.writeSync (C:\Users\westd\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:377:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\westd\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1099:19)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\westd\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\westd\AppData\Local\atom\app-1.7.3\resources\app.asar\src\text-editor.js:660:26)
    at Utility.module.exports.Utility.saveFile (C:\Users\westd\.atom\packages\ruby-test\lib\utility.coffee:4:15)
    at RubyTestView.module.exports.RubyTestView.saveFile (C:\Users\westd\.atom\packages\ruby-test\lib\ruby-test-view.coffee:115:10)
    at RubyTestView.module.exports.RubyTestView.runTest (C:\Users\westd\.atom\packages\ruby-test\lib\ruby-test-view.coffee:68:6)
    at RubyTestView.module.exports.RubyTestView.testFile (C:\Users\westd\.atom\packages\ruby-test\lib\ruby-test-view.coffee:53:6)
    at atom-workspace.<anonymous> (C:\Users\westd\.atom\packages\ruby-test\lib\ruby-test-view.coffee:24:68)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\westd\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\westd\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\westd\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\westd\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\westd\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\westd\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\westd\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\westd\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\westd\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\westd\AppData\Local\atom\app-1.7.3\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\westd\AppData\Local\atom\app-1.7.3\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:25.7.0 fuzzy-finder:toggle-file-finder (div.panels-item)
     -0:22.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:22.4.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:22.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:21.1.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 10x -0:20.5.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:19.7.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:19.5.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:18.2.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:14.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:13.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.5.0 ruby-test:test-file (atom-text-editor.editor.vim-mode.normal-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "ruby-test": {
    "cucumberFileCommand": "cucumber -p gold_manual_chrome"
  }
}
```

### Installed Packages

```coffee
# User
cucumber, v0.5.0
cucumber-autocomplete, v0.6.3
ruby-test, v0.9.17
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by moxley** [comment]
@dbwest: Is `dsfasdf` the name of your test file?
